 
version: "3.2"
services:
  frontend:
    image: congmeng1015/amazonscrapper-frontend:prod
    container_name: scrapper_app
    ports:
      - "3000:3000"
    depends_on:
      - controller
  controller:
    image: congmeng1015/amazonscrapper:prod
    container_name: scrapper_springboot
    ports:
      - "8080:8080"
    volumes:
      - $HOME/docker/volumes/log:/var/log
    depends_on:
      - database
  database:
    image: postgres
    container_name: database
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
      - $HOME/docker/volumes/db_backup:/var/db_backup
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5